# Generated by Django 3.0.5 on 2020-04-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20200407_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='company',
            field=models.CharField(max_length=300),
        ),
    ]
